language: node_js
node_js:
  - '10.2'

os:
  - linux
  - osx
  - windows

notifications:
  email: false

addons:
  apt:
    packages:
      - xvfb

env:
  - DISPLAY=":99.0"

install:
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
  - npm run build:prod

deploy:
  provider: script
  script: npm run dist:publish
  skip_cleanup: true
  on:
    # node: '10'
    # repo: dat-land/dat-desktop
    # branch: react
    # tags: true
