language: node_js
node_js:
- '8'
- '10'

os:
- linux
- osx

notifications:
  email: false

addons:
  apt:
    packages:
    - xvfb

env:
  - DISPLAY=":99.0"

install:
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

deploy:
  provider: script
  script: npm run dist
  skip_cleanup: true
  